plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mysms.app'
    compileSdk 36

    defaultConfig {
        applicationId 'com.mysms.app'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
}
