package com.mysms.app;

import android.Manifest;
import android.app.role.RoleManager;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.os.Bundle;
import android.provider.Telephony;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import androidx.activity.result.ActivityResultLauncher;
import androidx.activity.result.contract.ActivityResultContracts;
import androidx.appcompat.app.AppCompatActivity;
import com.google.android.material.button.MaterialButton;
import com.google.android.material.card.MaterialCardView;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;

public class MainActivity extends AppCompatActivity {
    private final int ink=Color.rgb(30,35,48), muted=Color.rgb(112,119,137), canvas=Color.rgb(248,249,252), primary=Color.rgb(75,76,190), line=Color.rgb(228,230,238);
    private SmsRepository repository; private LinearLayout root; private List<SmsRepository.Conversation> conversations=new ArrayList<>();
    private final ActivityResultLauncher<String[]> permissionLauncher=registerForActivityResult(new ActivityResultContracts.RequestMultiplePermissions(), result -> { if(hasSmsAccess()) showInbox(""); else showPermissionGate("SMS access is required to read and send messages."); });
    private final ActivityResultLauncher<Intent> roleLauncher=registerForActivityResult(new ActivityResultContracts.StartActivityForResult(), result -> { if(hasSmsAccess()) showInbox(""); });

    @Override protected void onCreate(Bundle state){super.onCreate(state); repository=new SmsRepository(this); getWindow().setStatusBarColor(canvas); getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR); if(hasSmsAccess()) showInbox(""); else showPermissionGate("Give MySMS access to your messages to get started.");}
    private boolean hasSmsAccess(){return checkSelfPermission(Manifest.permission.READ_SMS)==PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.SEND_SMS)==PackageManager.PERMISSION_GRANTED;}
    private boolean hasContacts(){return checkSelfPermission(Manifest.permission.READ_CONTACTS)==PackageManager.PERMISSION_GRANTED;}
    private void requestAccess(){List<String> p=new ArrayList<>(); if(!hasSmsAccess()){p.add(Manifest.permission.READ_SMS);p.add(Manifest.permission.SEND_SMS);p.add(Manifest.permission.RECEIVE_SMS);} if(!hasContacts())p.add(Manifest.permission.READ_CONTACTS); permissionLauncher.launch(p.toArray(new String[0]));}
    private void requestDefaultSmsRole(){if(android.os.Build.VERSION.SDK_INT>=29){RoleManager rm=getSystemService(RoleManager.class);if(rm!=null&&rm.isRoleAvailable(RoleManager.ROLE_SMS)&&!rm.isRoleHeld(RoleManager.ROLE_SMS))roleLauncher.launch(rm.createRequestRoleIntent(RoleManager.ROLE_SMS));}else Toast.makeText(this,"Default SMS role is managed in system settings on this Android version.",Toast.LENGTH_LONG).show();}

    private void showPermissionGate(String message){root=base();LinearLayout s=column(24,30,24,0);s.addView(label("MySMS",32,ink,Typeface.BOLD));s.addView(label("Your private inbox, beautifully simple.",17,muted,Typeface.NORMAL),margin(0,12,0,28));MaterialCardView card=new MaterialCardView(this);card.setRadius(22);card.setCardElevation(0);card.setStrokeColor(line);card.setStrokeWidth(1);LinearLayout inside=column(20,20,20,20);inside.addView(label("Connect your messages",19,ink,Typeface.BOLD));inside.addView(label(message+"\n\nMySMS only reads the Android messaging provider after you grant access. Nothing is fabricated when provider data is available.",15,muted,Typeface.NORMAL),margin(0,10,0,18));MaterialButton allow=button("Allow access",primary);allow.setOnClickListener(v->requestAccess());inside.addView(allow);MaterialButton role=button("Set as default SMS app",Color.rgb(92,95,123));role.setOnClickListener(v->requestDefaultSmsRole());inside.addView(role,margin(0,10,0,0));card.addView(inside);s.addView(card);root.addView(s,new LinearLayout.LayoutParams(-1,-1));setContentView(root);}

    private void showInbox(String query){root=base();LinearLayout content=column(20,22,20,0);LinearLayout header=row();header.addView(label("MySMS",30,ink,Typeface.BOLD),weight(1));header.addView(iconButton("⌕",v->focusSearch()));header.addView(iconButton("＋",v->showCompose()));header.addView(iconButton("⋯",v->showSettings()));content.addView(header);TextView eyebrow=label("YOUR MESSAGES",11,muted,Typeface.BOLD);eyebrow.setLetterSpacing(.14f);content.addView(eyebrow,margin(0,28,0,10));EditText search=input("Search conversations");content.addView(search,margin(0,0,0,18));LinearLayout list=column(0,0,0,0);content.addView(list);root.addView(content,new LinearLayout.LayoutParams(-1,-2));setContentView(root);search.setText(query);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){populate(list,s.toString());}public void afterTextChanged(Editable e){}});repository.loadConversations(new SmsRepository.Callback<List<SmsRepository.Conversation>>(){public void onSuccess(List<SmsRepository.Conversation> value){runOnUiThread(()->{conversations=value;populate(list,search.getText().toString());});}public void onError(Exception e){runOnUiThread(()->showProviderError(list,"Could not read your message inbox. Check permissions and try again."));}});}
    private void populate(LinearLayout list,String query){list.removeAllViews();String q=query.toLowerCase(Locale.ROOT);int count=0;for(SmsRepository.Conversation c:conversations)if(q.isEmpty()||c.name.toLowerCase(Locale.ROOT).contains(q)||c.address.contains(q)||c.preview.toLowerCase(Locale.ROOT).contains(q)){list.addView(conversationRow(c));count++;}if(count==0){TextView empty=label(conversations.isEmpty()?"No messages yet\nYour real SMS inbox will appear here.":"No conversations found\nTry a name, number, or message.",16,muted,Typeface.NORMAL);empty.setGravity(Gravity.CENTER);list.addView(empty,margin(0,48,0,0));}}
    private void showProviderError(LinearLayout list,String text){list.removeAllViews();TextView error=label(text+"\n\nTap ⋯ to review access.",15,muted,Typeface.NORMAL);error.setGravity(Gravity.CENTER);list.addView(error,margin(0,48,0,0));}
    private View conversationRow(SmsRepository.Conversation c){LinearLayout r=row();r.setPadding(0,12,0,12);r.setOnClickListener(v->showChat(c));r.addView(avatar(initials(c.name),52),margin(0,0,16,0));LinearLayout text=column(0,0,0,0);LinearLayout top=row();top.addView(label(c.name,16,ink,c.unread?Typeface.BOLD:Typeface.NORMAL),weight(1));top.addView(label(formatTime(c.time),12,muted,Typeface.NORMAL));text.addView(top);TextView preview=label(c.preview,14,c.unread?ink:muted,c.unread?Typeface.BOLD:Typeface.NORMAL);preview.setMaxLines(1);text.addView(preview,margin(0,5,0,0));r.addView(text,weight(1));if(c.unread)r.addView(label("●",13,primary,Typeface.BOLD),margin(10,0,0,0));return r;}

    private void showChat(SmsRepository.Conversation c){root=base();LinearLayout screen=column(18,14,18,0);LinearLayout bar=row();bar.addView(iconButton("‹",v->showInbox("")));bar.addView(avatar(initials(c.name),42),margin(8,0,12,0));LinearLayout who=column(0,0,0,0);who.addView(label(c.name,17,ink,Typeface.BOLD));who.addView(label(c.address,12,muted,Typeface.NORMAL));bar.addView(who,weight(1));bar.addView(iconButton("⋯",v->Toast.makeText(this,"Conversation actions",Toast.LENGTH_SHORT).show()));screen.addView(bar);ScrollView messages=new ScrollView(this);LinearLayout thread=column(0,4,0,20);messages.addView(thread);screen.addView(messages,new LinearLayout.LayoutParams(-1,0,1));LinearLayout composer=row();composer.setGravity(Gravity.CENTER_VERTICAL);composer.setPadding(8,8,8,8);MaterialCardView card=new MaterialCardView(this);card.setRadius(28);card.setCardElevation(0);card.setStrokeColor(line);card.setStrokeWidth(1);EditText input=input("Message");card.addView(input,new ViewGroup.LayoutParams(-1,-2));composer.addView(card,new LinearLayout.LayoutParams(0,56,1));MaterialButton send=button("↑",primary);send.setMinWidth(56);send.setOnClickListener(v->{String body=input.getText().toString().trim();if(body.isEmpty())return;sendMessage(c,body,thread,input,messages);});composer.addView(send,margin(8,0,0,0));screen.addView(composer);root.addView(screen,new LinearLayout.LayoutParams(-1,-1));setContentView(root);repository.markThreadRead(c.threadId);repository.loadMessages(c.threadId,new SmsRepository.Callback<List<SmsRepository.Message>>(){public void onSuccess(List<SmsRepository.Message> ms){runOnUiThread(()->{thread.removeAllViews();if(ms.isEmpty())thread.addView(label("No messages in this conversation.",15,muted,Typeface.NORMAL),margin(0,48,0,0));for(SmsRepository.Message m:ms)addBubble(thread,m.body,m.isOutgoing(),formatTime(String.valueOf(m.date)));});}public void onError(Exception e){runOnUiThread(()->{thread.removeAllViews();thread.addView(label("Unable to load this conversation.",15,muted,Typeface.NORMAL),margin(0,48,0,0));});}});}
    private void sendMessage(SmsRepository.Conversation c,String body,LinearLayout thread,EditText input,ScrollView messages){addBubble(thread,body,true,"Sending…");input.setText("");messages.post(()->messages.fullScroll(View.FOCUS_DOWN));repository.send(c.address,body,new SmsRepository.Callback<Void>(){public void onSuccess(Void v){runOnUiThread(()->Toast.makeText(MainActivity.this,"Message sent",Toast.LENGTH_SHORT).show());}public void onError(Exception e){runOnUiThread(()->Toast.makeText(MainActivity.this,"Message failed. Check signal and try again.",Toast.LENGTH_LONG).show());}});}
    private void addBubble(LinearLayout thread,String text,boolean sent,String time){LinearLayout lr=row();lr.setGravity(sent?Gravity.END:Gravity.START);LinearLayout b=column(0,0,0,0);b.setPadding(dp(16),dp(12),dp(16),dp(10));b.setBackgroundColor(sent?primary:Color.WHITE);b.addView(label(text,16,sent?Color.WHITE:ink,Typeface.NORMAL));b.addView(label(time,11,sent?Color.rgb(218,218,255):muted,Typeface.NORMAL),margin(0,5,0,0));lr.addView(b);thread.addView(lr,margin(0,4,0,4));}

    private void showCompose(){root=base();LinearLayout s=column(20,18,20,0);LinearLayout bar=row();bar.addView(iconButton("‹",v->showInbox("")));bar.addView(label("New message",22,ink,Typeface.BOLD),weight(1));s.addView(bar);s.addView(label("TO",11,muted,Typeface.BOLD),margin(0,28,0,8));EditText to=input("Name or phone number");s.addView(to,margin(0,0,0,18));s.addView(label("MESSAGE",11,muted,Typeface.BOLD),margin(0,0,0,8));EditText body=input("Write something kind…");s.addView(body,margin(0,0,0,22));MaterialButton send=button("Send message",primary);send.setOnClickListener(v->{String destination=to.getText().toString().trim(),text=body.getText().toString().trim();if(destination.isEmpty()||text.isEmpty()){Toast.makeText(this,"Add a recipient and message first.",Toast.LENGTH_SHORT).show();return;}repository.send(destination,text,new SmsRepository.Callback<Void>(){public void onSuccess(Void x){runOnUiThread(()->{Toast.makeText(MainActivity.this,"Message sent",Toast.LENGTH_SHORT).show();showInbox("");});}public void onError(Exception e){runOnUiThread(()->Toast.makeText(MainActivity.this,"Message failed. Check permissions and signal.",Toast.LENGTH_LONG).show());}});});s.addView(send);root.addView(s,new LinearLayout.LayoutParams(-1,-1));setContentView(root);}
    private void showSettings(){root=base();LinearLayout s=column(20,18,20,0);LinearLayout bar=row();bar.addView(iconButton("‹",v->showInbox("")));bar.addView(label("Settings",22,ink,Typeface.BOLD),weight(1));s.addView(bar);s.addView(label("MESSAGING ACCESS",11,muted,Typeface.BOLD),margin(0,30,0,12));addSetting(s,"SMS permissions",hasSmsAccess()?"Granted":"Needs attention");addSetting(s,"Contacts",hasContacts()?"Granted":"Optional — tap to allow names");addSetting(s,"Default SMS app",Telephony.Sms.getDefaultSmsPackage(this)!=null&&Telephony.Sms.getDefaultSmsPackage(this).equals(getPackageName())?"MySMS is default":"Not MySMS");MaterialButton role=button("Review default SMS role",Color.rgb(92,95,123));role.setOnClickListener(v->requestDefaultSmsRole());s.addView(role,margin(0,6,0,0));s.addView(label("MySMS 1.0 · Real provider data",12,muted,Typeface.NORMAL),margin(0,34,0,0));root.addView(s,new LinearLayout.LayoutParams(-1,-1));setContentView(root);}
    private void addSetting(LinearLayout p,String title,String sub){MaterialCardView card=new MaterialCardView(this);card.setRadius(18);card.setCardElevation(0);card.setStrokeColor(line);card.setStrokeWidth(1);LinearLayout r=column(16,15,16,15);r.addView(label(title,16,ink,Typeface.BOLD));r.addView(label(sub,13,muted,Typeface.NORMAL),margin(0,4,0,0));card.addView(r);p.addView(card,margin(0,0,0,10));}
    private void focusSearch(){showInbox("");}
    private LinearLayout base(){LinearLayout b=column(0,0,0,0);b.setBackgroundColor(canvas);return b;} private LinearLayout column(int l,int t,int r,int bot){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(l),dp(t),dp(r),dp(bot));return x;} private LinearLayout row(){return new LinearLayout(this){{setOrientation(LinearLayout.HORIZONTAL);}};} private TextView label(String s,int size,int color,int style){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setTypeface(Typeface.DEFAULT,style);v.setGravity(Gravity.CENTER_VERTICAL);return v;} private TextView avatar(String s,int size){TextView v=label(s,size/3,ink,Typeface.BOLD);v.setGravity(Gravity.CENTER);v.setBackgroundColor(Color.rgb(205,196,232));v.setMinWidth(dp(size));v.setMinHeight(dp(size));return v;} private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(15);e.setSingleLine(false);e.setPadding(dp(16),dp(7),dp(16),dp(7));e.setBackgroundColor(Color.WHITE);e.setTextColor(ink);e.setHintTextColor(muted);return e;} private TextView iconButton(String text,View.OnClickListener l){TextView v=label(text,28,ink,Typeface.NORMAL);v.setGravity(Gravity.CENTER);v.setContentDescription(text);v.setOnClickListener(l);v.setPadding(dp(7),0,dp(7),0);return v;} private MaterialButton button(String text,int color){MaterialButton b=new MaterialButton(this);b.setText(text);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setBackgroundColor(color);return b;} private LinearLayout.LayoutParams weight(float w){return new LinearLayout.LayoutParams(0,-2,w);} private LinearLayout.LayoutParams margin(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;} private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} private String initials(String n){String[] a=n.trim().split(" ");return a.length>1?(a[0].substring(0,1)+a[a.length-1].substring(0,1)).toUpperCase(Locale.ROOT):n.substring(0,Math.min(2,n.length())).toUpperCase(Locale.ROOT);} private String formatTime(String raw){try{return DateFormat.getTimeInstance(DateFormat.SHORT).format(new Date(Long.parseLong(raw)));}catch(Exception e){return raw;}}
}
